issues = [
    "billing issue",
    "account issue",
    "software issue",
    "app issue",
    "hardware issue",
    "network issue",
]

devices = [
    "iphone",
    "ipad",
    "macbook pro",
    "mackbook air",
    "imac",
    "mac pro",
    "airpods",
    "homepod",
    "apple tv",
    "apple watch"
]

positive_sequences = [
    "The agent was incredibly helpful.",
    "Quick and efficient service!",
    "Solved my problem right away.",
    "Friendly and professional interaction.",
    "Went above and beyond to assist me.",
    "I'm really satisfied with the support I received.",
    "The representative made everything clear and simple.",
    "Great experience! I felt listened to.",
    "I appreciate the timely response and resolution.",
    "The support team was very attentive to my needs.",
    "Exceptional service from a knowledgeable agent.",
    "I was treated with respect and empathy.",
    "Everything was handled with care and precision.",
    "The agent's expertise really shone through.",
    "I felt like a valued customer.",
    "The support exceeded my expectations.",
    "They made sure I understood everything.",
    "I was pleasantly surprised by the dedication of the team.",
    "The agent took the time to understand my situation.",
    "Thank you for making a complex issue seem simple."
]

neutral_sequences = [
    "The call was okay.",
    "Service was as expected.",
    "I got what I needed.",
    "Neither good nor bad; it was fine.",
    "Typical call center experience.",
    "The agent did what was required.",
    "Nothing special, but my issue was resolved.",
    "The call was neither pleasant nor unpleasant.",
    "It was just a standard support call.",
    "I didn't have any problems, but nothing stood out.",
    "The support was adequate.",
    "Everything went as I anticipated.",
    "No complaints, but also no compliments.",
    "The service was functional and basic.",
    "The agent was professional but not particularly engaging.",
    "I got the information I needed, nothing more or less.",
    "It was a routine support experience.",
    "The process was straightforward but not memorable.",
    "I don't have strong feelings about the experience.",
    "The call was handled in a usual manner."
]

negative_sequences = [
    "I was on hold forever.",
    "The agent was rude and unhelpful.",
    "Didn't resolve my issue at all.",
    "Misinformation provided; I'm frustrated.",
    "No follow-through on promises made.",
    "The support was confusing and slow.",
    "I felt ignored and unimportant.",
    "The agent seemed uninterested in helping me.",
    "I'm very dissatisfied with the service I received.",
    "The call made my problem even worse.",
    "I had to repeat myself multiple times.",
    "The agent kept interrupting me.",
    "I was passed around without any resolution.",
    "Terrible experience; I'm very disappointed.",
    "The support team seemed uninformed and careless.",
    "I never received the follow-up I was promised.",
    "The agent was condescending and impatient.",
    "I wasted a lot of time without getting help.",
    "The whole process was frustrating and unprofessional.",
    "I was left feeling more confused than before."
]

positive_templates = [
    "I called about my {device} having {issue}, and {positive_sequence}.",
    "My experience with {device} {issue} was great because {positive_sequence}.",
    "Regarding the {issue} with my {device}, {positive_sequence}.",
    "I had an {issue} with my {device}, but the support team was amazing: {positive_sequence}.",
    "The agent helped me with my {device}'s {issue} and {positive_sequence}.",
    "I reached out for support with my {device} and {issue}, and {positive_sequence}.",
    "My {device} had an {issue}, but the help I received was excellent: {positive_sequence}.",
    "I needed assistance with my {device}'s {issue}, and {positive_sequence}.",
    "The {issue} on my {device} was quickly handled; {positive_sequence}.",
    "I spoke with an agent about my {device}'s {issue}, and {positive_sequence}.",
    "I was experiencing {issue} with my {device}, but {positive_sequence}.",
    "I contacted support for my {device} {issue}, and {positive_sequence}.",
    "I was worried about my {device}'s {issue}, but the agent {positive_sequence}.",
    "I had a concern about {issue} on my {device}, and the response was great: {positive_sequence}.",
    "I required support for {issue} with my {device}, and {positive_sequence}.",
    "I encountered {issue} with my {device}, but the support was outstanding: {positive_sequence}.",
    "My {device} was facing {issue}, but the agent's assistance was excellent: {positive_sequence}.",
    "I reached out regarding {issue} on my {device}, and {positive_sequence}.",
    "I needed help with my {device}'s {issue}, and the agent's response was: {positive_sequence}.",
    "My call was about {issue} with my {device}, and {positive_sequence}."
]

neutral_templates = [
    "I called about my {device} having {issue}, and {neutral_sequence}.",
    "Regarding the {issue} with my {device}, {neutral_sequence}.",
    "I had an {issue} with my {device}, and the support was okay: {neutral_sequence}.",
    "The agent assisted me with my {device}'s {issue}, and {neutral_sequence}.",
    "I reached out for help with my {device} and {issue}, and {neutral_sequence}.",
    "My {device} had an {issue}, and the help I received was adequate: {neutral_sequence}.",
    "I needed assistance with my {device}'s {issue}, and {neutral_sequence}.",
    "The {issue} on my {device} was handled, but {neutral_sequence}.",
    "I spoke with an agent about my {device}'s {issue}, and {neutral_sequence}.",
    "I was experiencing {issue} with my {device}, and {neutral_sequence}.",
    "I contacted support for my {device} {issue}, and {neutral_sequence}.",
    "I was concerned about my {device}'s {issue}, and the agent {neutral_sequence}.",
    "I had a question about {issue} on my {device}, and the response was: {neutral_sequence}.",
    "I required support for {issue} with my {device}, and {neutral_sequence}.",
    "I encountered {issue} with my {device}, and the support was just okay: {neutral_sequence}.",
    "My {device} was having {issue}, and the agent's assistance was standard: {neutral_sequence}.",
    "I reached out regarding {issue} on my {device}, and {neutral_sequence}.",
    "I needed help with my {device}'s {issue}, and the agent's response was: {neutral_sequence}.",
    "My call was about {issue} with my {device}, and {neutral_sequence}.",
    "I had a problem with {issue} on my {device}, and the service was typical: {neutral_sequence}."
]

negative_templates = [
    "I called about my {device} having {issue}, and {negative_sequence}.",
    "Regarding the {issue} with my {device}, {negative_sequence}.",
    "I had an {issue} with my {device}, and the support was terrible: {negative_sequence}.",
    "The agent failed to help me with my {device}'s {issue}, and {negative_sequence}.",
    "I reached out for help with my {device} and {issue}, and {negative_sequence}.",
    "My {device} had an {issue}, and the help I received was unsatisfactory: {negative_sequence}.",
    "I needed assistance with my {device}'s {issue}, and {negative_sequence}.",
    "The {issue} on my {device} was mishandled, and {negative_sequence}.",
    "I spoke with an agent about my {device}'s {issue}, and {negative_sequence}.",
    "I was experiencing {issue} with my {device}, and {negative_sequence}.",
    "I contacted support for my {device} {issue}, and {negative_sequence}.",
    "I was upset about my {device}'s {issue}, and the agent {negative_sequence}.",
    "I had a major problem with {issue} on my {device}, and the response was: {negative_sequence}.",
    "I required support for {issue} with my {device}, and {negative_sequence}.",
    "I encountered {issue} with my {device}, and the support was frustrating: {negative_sequence}.",
    "My {device} was having {issue}, and the agent's assistance was terrible: {negative_sequence}.",
    "I reached out regarding {issue} on my {device}, and {negative_sequence}.",
    "I needed help with my {device}'s {issue}, and the agent's response was: {negative_sequence}.",
    "My call was about {issue} with my {device}, and {negative_sequence}.",
    "I had a horrible experience with {issue} on my {device}, and the service was: {negative_sequence}."
]
